import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useStoreAnimals = defineStore('animals', () => {
  const animals = ref([
    {
      id: 'an1',
      name: 'Alpine ibex',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/5/5b/Alpine_ibex_male_common.png',
      maxWeight: '120kg',
      minScore: 43,
      taxScore: 270,
      maxScore: 292,
      rares: 'Albino',
      otherFurs: 'Dark',
    },
    {
      id: 'an2',
      name: 'American Black Duck',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/2/2b/American_black_duck_male_common.png',
      maxWeight: '1.6kg',
      minScore: 750,
      taxScore: 1525,
      maxScore: 1600,
      rares: 'Albino, Mallard Hybrid',
      otherFurs: '',
    },
    {
      id: 'an3',
      name: 'Arctic Fox',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/bb/Arctic_fox_male_common.png',
      maxWeight: '8kg',
      minScore: 3,
      taxScore: 16,
      maxScore: 18,
      rares: '',
      otherFurs: 'Blue',
    },
    {
      id: 'an4',
      name: 'Axis Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/e/ed/Axis_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an5',
      name: 'Banteng',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/b1/Banteng_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an6',
      name: 'Bighorn Sheep',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/d/de/Bighorn_sheep_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an7',
      name: 'Bison',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/cd/Bison_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an8',
      name: 'Black Bear',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/1/10/Black_bear_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an9',
      name: 'Blacktail Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/0/08/Blacktail_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an10',
      name: 'Bobcat',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/f/fb/Bobcat_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an11',
      name: 'Brown Bear',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/2/2d/Brown_bear_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an12',
      name: 'Canada Goose',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/a/a0/Canada_goose_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an13',
      name: 'Cottontail Rabbit',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/1/13/Cottontail_rabbit_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an14',
      name: 'Coyote',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/6/6d/Coyote_male_common.png', 
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an15',
      name: 'Dall Sheep',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/ba/Dall_sheep_male_common.png', 
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an16',
      name: 'Eurasian Lynx',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/5/52/Eurasian_lynx_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an17',
      name: 'European Rabbit',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/9/9b/European_rabbit_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an18',
      name: 'Fallow Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/cd/Fallow_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an19',
      name: 'Feral Goat',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/c0/Feral_goat_male_brown.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an20',
      name: 'Feral Hog',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/7/71/Feral_hog_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an21',
      name: 'Gadwall',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/6/64/Gadwall_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an22',
      name: 'Grey Wolf',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/3/3a/Grey_wolf_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an23',
      name: 'Grizzly Bear',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/4/4f/Grizzly_bear_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an24',
      name: 'Magpie Goose',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/9/98/Magpie_goose_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an25',
      name: 'Mallard Duck',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/bf/Mallard_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an26',
      name: 'Moose',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/a/a8/Moose_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an27',
      name: 'Mule Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/b6/Mule_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an28',
      name: 'Northern Pintail',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/8/83/Northern_pintail_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an29',
      name: 'Pheasant',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/c4/Pheasant_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an30',
      name: 'Polar Bear',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/4/4f/Polar_bear_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an31',
      name: 'Puma',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/6/67/Puma_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an32',
      name: 'Red Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/8/82/Red_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an33',
      name: 'Red Fox',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/1/10/Red_fox_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an34',
      name: 'Red Kangaroo',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/8/88/Red_kangaroo_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an35',
      name: 'Reindeer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/9/9a/Reindeer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an36',
      name: 'Rock Ptarmigan',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/2/21/Rock_ptarmigan_male_common.png/',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an37',
      name: 'Rocky Mountain Elk',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/1/1b/Rocky_mountain_elk_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an38',
      name: 'Roe Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/d/dc/Roe_deer_male_common.png/',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an39',
      name: 'Roosevelt Elk',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/b/b6/Roosevelt_elk_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an40',
      name: 'Rusa Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/cc/Rusa_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an41',
      name: 'Sambar Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/d/dc/Sambar_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an42',
      name: 'Sitka Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/a/a4/Sitka_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an43',
      name: 'Snow Goose',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/5/59/Snow_goose_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an44',
      name: 'Snowshoe Hare',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/f/f7/Snowshoe_hare_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an45',
      name: 'Turkey',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/f/f2/Turkey_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an46',
      name: 'Water Buffalo',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/c/c9/Water_buffalo_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an47',
      name: 'Whitetail Deer',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/0/0b/Whitetail_deer_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an48',
      name: 'White-tailed Ptarmigan',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/a/a8/White-tailed_ptarmigan_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an49',
      name: 'Wild Boar',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/a/a3/Wild_boar_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an50',
      name: 'Willow Ptarmigan',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/5/58/Willow_ptarmigan_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
    {
      id: 'an51',
      name: 'Wood Grouse',
      imageURL: 'https://static.wikia.nocookie.net/thehuntergame/images/9/95/Wood_grouse_male_common.png',
      maxWeight: '110kg',
      minScore: 20,
      taxScore: 200,
      maxScore: 215,
      rares: 'Albino, Melanistic, Piebald',
      otherFurs: 'Dark (M), Orange (F)',
    },
  ])

  return { animals }
})
