import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useStoreWeapons = defineStore('weapons', () => {
  const weaponTypes = {
    t1: {
      name: 'Varmint Rifles',
      weapons: ['w1', 'w2', 'w3', 'w4', 'w5'], // 5
    },
    t2: {
      name: 'Bolt Action Rifles',
      weapons: ['w6', 'w7', 'w8', 'w9', 'w10', 'w11', 'w12', 'w13', 'w14', 'w15', 'w16', 'w17'], // 12
    },
    t3: {
      name: 'Lever Action Rifles',
      weapons: ['w18', 'w19', 'w20', 'w21'], // 4
    },
    t4: {
      name: 'Break Action Rifles',
      weapons: ['w22', 'w23', 'w24'], // 3
    },
    t5: {
      name: 'Classic Rifles',
      weapons: ['w25', 'w26', 'w27', 'w28', 'w29', 'w30'], // 6
    },
    t6: {
      name: 'Advanced Firearms',
      weapons: ['w31', 'w32'], // 2
    },
    t7: {
      name: 'Shotguns',
      weapons: ['w33', 'w34', 'w35', 'w36', 'w37', 'w38', 'w39', 'w40'], // 8
    },
    t8: {
      name: 'Handguns',
      weapons: ['w41', 'w42', 'w43', 'w44', 'w45', 'w46', 'w47'], // 7
    },
    t9: {
      name: 'Muzzleloaders',
      weapons: ['w48', 'w49', 'w50'], // 3
    },
    t10: {
      name: 'Bows',
      weapons: ['w51', 'w52', 'w53', 'w54', 'w55', 'w56', 'w57', 'w58'], // 8
    },
    t11: {
      name: 'Crossbows',
      weapons: ['w59', 'w60', 'w61'], // 8
    },
  };
  const weapons = ref([
    {
      id: 'w1',
      type: 't1',
      name: '.223 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_223_02.png',
      priceGM: 7650,
      priceEM: 450,
      ammunition: ['am1'],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: true
    },
    {
      id: 'w2',
      type: 't1',
      name: '.223 Semi-Automatic Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/semi_auto_rifle_223_02.png',
      priceGM: 9350,
      priceEM: 550,
      ammunition: ['am1'],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: true
    },
    {
      id: 'w3',
      type: 't1',
      name: '.17 HMR Lever Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/lever_action_rifle_17_HMR.png',
      priceGM: 9350,
      priceEM: 550,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: true
    },
    {
      id: 'w4',
      type: 't1',
      name: '.22 Semi-Automatic Rifle Plinkington',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_semi_auto_03.png',
      priceGM: 9350,
      priceEM: 550,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: true
    },
    {
      id: 'w5',
      type: 't1',
      name: '.22 Air Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_22_air_01.png',
      priceGM: 7650,
      priceEM: 450,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: true
    },
    {
      id: 'w6',
      type: 't2',
      name: '.243 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_243.png',
      priceGM: 2550,
      priceEM: 150,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: true,
      owned: true
    },
    {
      id: 'w7',
      type: 't2',
      name: '.270 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifleboltwin_270_02.png',
      priceGM: 9333,
      priceEM: 549,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w8',
      type: 't2',
      name: '.300 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_300.png',
      priceGM: 11050,
      priceEM: 650,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w9',
      type: 't2',
      name: '.308 Anschütz 1780 D FL Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_308_anschutz.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w10',
      type: 't2',
      name: '.308 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_308_04.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w11',
      type: 't2',
      name: '6.5x55 Blaser R8 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_blaser_r8_01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w12',
      type: 't2',
      name: '6.5x55 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_bolt_action_panther.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w13',
      type: 't2',
      name: '7mm Magnum Bullpup Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bullpup01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w14',
      type: 't2',
      name: '7x64mm Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_7x64.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w15',
      type: 't2',
      name: '8x57 IS Anschütz 1780 D FL Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_8x57_anschutz.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w16',
      type: 't2',
      name: '9.3x62 Anschütz 1780 D FL Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_93x62_anschutz.png',
      priceGM: 11900,
      priceEM: 700,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w17',
      type: 't2',
      name: '.340 Weatherby Magnum Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_340.png',
      priceGM: 11050,
      priceEM: 650,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w18',
      type: 't3',
      name: '.30-30 Lever Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/riflelever_3030_01.png',
      priceGM: 8500,
      priceEM: 500 ,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w19',
      type: 't3',
      name: '.30-06 Lever Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifleleverwin_270.png',
      priceGM: 9350,
      priceEM: 550,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w20',
      type: 't3',
      name: '.405 Lever Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/lever_action_rifle_405.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w21',
      type: 't3',
      name: '.45-70 Government Lever Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/riflelever_4570_01.png',
      priceGM: 10183,
      priceEM: 599,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w22',
      type: 't4',
      name: '7mm Magnum Break Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/break_action_01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w23',
      type: 't4',
      name: '.30 R O/U Break Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/break_action_rifle_30R.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w24',
      type: 't4',
      name: '9.3x74R O/U Break Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/break_action_93x74r.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w25',
      type: 't5',
      name: '.30-06 Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_30x06_01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w26',
      type: 't5',
      name: '.30-06 Stutzen Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/steyr_stutzen.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w27',
      type: 't5',
      name: '7.62x54R Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bolt_action_rifle_762_01.png',
      priceGM: 9350,
      priceEM: 550,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w28',
      type: 't5',
      name: '8x57 IS K98k Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_8x57_k98k.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w29',
      type: 't5',
      name: '.303 British Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/rifle_303.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w30',
      type: 't5',
      name: '.45-70 Buffalo Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/lever_action_rifle_buffalo.png',
      priceGM: 10183,
      priceEM: 599,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w31',
      type: 't6',
      name: '16GA/9.3x74R Drilling',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/combination_gun_93x74r_16ga.png',
      priceGM: 15283,
      priceEM: 899,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w32',
      type: 't6',
      name: '7mm-08 Scout Bolt Action Rifle',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/scout_rifle.png',
      priceGM: 13583,
      priceEM: 799,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w33',
      type: 't7',
      name: '10 GA Lever Action Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun_lever_action_10ga.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w34',
      type: 't7',
      name: '12 GA Pump Action Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun12bore.png',
      priceGM: 7650,
      priceEM: 450,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w35',
      type: 't7',
      name: 'Maisto 12 GA Semi-Automatic Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun_12ga_sa_wood.png',
      priceGM: 11050,
      priceEM: 650,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w36',
      type: 't7',
      name: '12 GA Side By Side Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun02.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w37',
      type: 't7',
      name: '12 GA Blaser F3 Game O/U Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun_oau_12ga_01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w38',
      type: 't7',
      name: '12 GA Single Shot Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/single_shot_shotgun_01.png',
      priceGM: 0,
      priceEM: 0,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: true,
      owned: true
    },
    {
      id: 'w39',
      type: 't7',
      name: '16 GA Side By Side Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun_sbs_16ga.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w40',
      type: 't7',
      name: '20 GA Semi-Automatic Shotgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/shotgun_semi_auto_20ga_carbon.png',
      priceGM: 11050,
      priceEM: 650,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w41',
      type: 't8',
      name: '.22 Pistol',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/pistol_22_01.png',
      priceGM: 6800,
      priceEM: 400,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w42',
      type: 't8',
      name: '.357 Revolver',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/357magnum.png',
      priceGM: 5950,
      priceEM: 350,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w43',
      type: 't8',
      name: '.44 Revolver',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/handgun_44_01.png',
      priceGM: 8925,
      priceEM: 525,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w44',
      type: 't8',
      name: '.45 Long Colt Revolver',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/454classic_01.png',
      priceGM: 9775,
      priceEM: 575,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w45',
      type: 't8',
      name: '.454 Revolver',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/454revolver02.png',
      priceGM: 9775,
      priceEM: 575,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w46',
      type: 't8',
      name: '.308 Handgun',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/handgun_308_01.png',
      priceGM: 10625,
      priceEM: 625,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w47',
      type: 't8',
      name: '10mm Semi-Automatic Pistol',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/10mm_semi_automatic_pistol.png',
      priceGM: 9775,
      priceEM: 575,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w48',
      type: 't9',
      name: '.50 Cap Lock Muzzleloader',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/muzzleloader01.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w49',
      type: 't9',
      name: '.50 Inline Muzzleloader',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/inline_muzzleloader01.png',
      priceGM: 11900,
      priceEM: 700,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w50',
      type: 't9',
      name: '.50 Inline Muzzleloading Pistol',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/muzzlepistol_50_lead.png',
      priceGM: 11050,
      priceEM: 650,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w51',
      type: 't10',
      name: 'Compound Bow Snakebite',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bow.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w52',
      type: 't10',
      name: 'Compound Bow Parker Python',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bow_parker_python.png',
      priceGM: 11900,
      priceEM: 700,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w53',
      type: 't10',
      name: 'Compound Bow Red Dragon',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bow_red_dragon.png',
      priceGM: 11900,
      priceEM: 700,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w54',
      type: 't10',
      name: 'Compound Bow Pulsar',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/compound_bow_pulsar_forest_camo.png',
      priceGM: 10200,
      priceEM: 600,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w55',
      type: 't10',
      name: 'Heavy Recurve Bow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bow_recurve_04.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w56',
      type: 't10',
      name: 'Recurve Bow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/bow_recurve_01.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w57',
      type: 't10',
      name: 'Longbow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/long_bow_01.png',
      priceGM: 8925,
      priceEM: 525,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w58',
      type: 't10',
      name: 'Cable-backed Bow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/cable_back_bow_01.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w59',
      type: 't11',
      name: 'Reverse Draw Crossbow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/crossbow_03.png',
      priceGM: 8823,
      priceEM: 519,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w60',
      type: 't12',
      name: 'Tenpoint Carbon Fusion Crossbow',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/crossbow_01.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
    {
      id: 'w61',
      type: 't12',
      name: 'Crossbow Pistol',
      imgUrl: 'https://static.thehunter.com/static/img/items/1024/crossbow_pistol_01.png',
      priceGM: 8500,
      priceEM: 500,
      ammunition: [],
      animals: [],
      missions: [],
      scopes: [],
      selected: false,
      owned: false
    },
  ])

  
  // const selectRifle = computed(() => count.value * 2)
  function selectRifle(id) {
    weapons.value.forEach(weapon => {
      if(weapon.id === id){
        weapon.selected = !weapon.selected
      }
    })
  }

  const selectedWeapons = computed(() => weapons.value.filter(w => w.selected).map(w => w.id))

  return { weaponTypes, weapons, selectRifle, selectedWeapons }
})
